
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos7.3-x86_64"
  #config.vm.box = "centos/7"
  config.vm.hostname = "puppetserver"
  config.vm.network "public_network", bridge: "wlp3s0"
  #config.vm.network "private_network", ip: "192.168.0.10"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 1
  end

  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision :shell, :path => "puppet-bootstrap.sh"

#  config.vm.provision "puppet" do |puppet|
#    puppet.manifests_path = "puppet/manifests"
#    puppet.manifest_file = "site.pp"
#    puppet.module_path = "puppet/modules"
#  end

end
